language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "grace-shopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: the-armory # see README
  api_key:
    secure: "kNCOkDrjMnU1+sSO3iDvgktD+R41GaXbwblWFMjEQR6H/6QuYNVFRUp6Cyvxi0yTC2+2cJ7D+GLtPRHvoOffsgR6k0Jvh1Ly5l+E+sCmwJqmpfQOwlA+sBoQtc3B5BYmqd/Xv6YjtclDA48rb3bUMu/OgEJyMsF9qat6HqHXNShGFRmOHmP3/exRYNjjRWGh8C8FV7SONfEAYtFDN2aGliVKpY38bGQDnKvJ9vnaUKVIcoNX6TO8vJJ4AB6tR6mxMOwKHi7EeAeYibbiDoIjGFq+3d18nTtiXMvsptc46NrG7BVHlvB6lN28hBrcOTIGyZciUffAXd/Ebg/b3xGnVmyQT6yCsaEhfpf1xrkudRoQF+3hJ9JtU67l6kRGGgnhl88ArT57lT/2RZPfQI3udYYhU7F0gvG4n68TPyuiBFMUbj2KUqB4QNf97xJHdq/oa/r0gscrzpRF27nFKfUgRqmWmJ/fDloNvYZ+kQsV8Fcf6r0x5lD2Vy8Ed0bHvUqoMwBMdSTUfe4MN28g7jSZnFiSGPZ9tLhRy51a81UfRpc4JyTyPPRrsgoLk3DFs5JhVoxkRMRcy8LjU1pckPhiUYwSbud3jbKsnOZl/dg4aoKKovDFevYndBZorbqb+KJqzEnO2KoUrpC0ul3UlYBy+3jbbgTvZKxphciqOChXwHw=" # see README


